name: Deploy Frontend

on:
  push:
    branches:
      - main

env:
  AWS_REGION : "eu-west-1"

# required for AWS
permissions:
      id-token: write   
      contents: read    

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy frontend"
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume:  arn:aws:iam::381336380362:role/github-actions-chat-app-role
          role-session-name: GitHub_to_AWS_frontend_deployment
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build production build
        run: npm run build

      - name: Deploy to S3 bucket
        run: |
          S3_BUCKET_NAME="my-private-chat-app"
          LOCAL_FOLDER_PATH="build"

          # Install AWS CLI
          apt-get -q install -y awscli

          # Deploy to S3 bucket
          aws s3 sync "$LOCAL_FOLDER_PATH" "s3://$S3_BUCKET_NAME"
